### ISSUE TITLE
proper csv import behavior

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/sos#13]
@tom95858 @oceandlr 

I'm composing a python filter based on ldms store_csv KIND header.
I need to know the desired behavior in some corner cases where my own opinions aren't particularly strong.

case 1:  parse the csv header and kind lines and generate a matching schema from scratch. No obvious problems here, except I don't see how sos-import-csv supports importing numeric array values from a set of N columns. Did I miss something in how the map file is formatted, or is that just unsupported intentionally (at this stage?)? I can supply a list of indices that are the array element columns in order (and hence N is known).

case 2: User supplies a predefined schema to feed the csv into. Discarding metric set columns not named with the schema is easy. What needs to be done when there is no csv column for a name in the schema? Is this a user error for supplying us incompatible input, or is the absence of a metric from the map intended to be ok with SOS?

**Comment by tom95858** [comment]
There is a new map file format that supports importing into arrays and from arbitrary columns.

**Comment by baallan** [comment]
Thanks! I should be able to use that following the new man page.
