### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by MAChenliang** [ovis-hpc/sos#28]
Have I installed any less dependencies?

System version: centos 7.7
SOS version: sos-OVIS-4.3.1

yum install libtool python python-devel Cython libyaml libyaml-devel numpy
./autogen.sh 
mkdir build
cd build/
../configure --prefix=/opt/SOS
make
...
...
Compiler crash traceback from this point on:
  File "Visitor.py", line 168, in Cython.Compiler.Visitor.TreeVisitor._visit (/builddir/build/BUILD/Cython-0.19/Cython/Compiler/Visitor.c:4111)
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2294, in visit_LambdaNode
    self.create_class_from_scope(node.def_node, self.module_scope, node)
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2272, in create_class_from_scope
    type=cscope.scope_class.type,
AttributeError: 'ClosureScope' object has no attribute 'scope_class'
make[3]: *** [Sos.c] Error 1
make[3]: Leaving directory `/root/sos-OVIS-4.3.1/build/sos/python'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/sos-OVIS-4.3.1/build/sos'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/sos-OVIS-4.3.1/build'
make: *** [all] Error 2

**Comment by tom95858** [comment]
@MAChenliang can you please checkout the branch SOS-4 from https://github.com/ovis-hpc/sos.git and try again? This is the Cython compiler crashing. The Cython you have is a bit old 0.19.

This will get you the latest:

pip install --upgrade cython

**Comment by MAChenliang** [comment]
@tom95858  Sorry,I forgot to reply.SOS  was installed successfully after I updated cython.Thanks for your help.
