### ISSUE TITLE
Timestamp issue for csv-imported container

### ISSUE THREAD

**Issue by bschwal** [ovis-hpc/sos#36]
I created a MAPSOS and SCHEMASOS file to create a SOS container from a csv file. My timestamp column is set to be type:timestamp and to be indexed. When I am using numSOS to get_df with the container I am getting this error: 

"The time value is a floating point secs.usecs number"

Which tracks to these lines in sos/sos/python/Sos.pyx:

elif typ == float or typ == np.float64 or typ == np.float32:
        try:
            secs = int(val)
            usecs = int((val * 1.e6) - (secs * 1.e6))
        except:
            raise ValueError("The time value is a floating point secs.usecs number")

When I query the container with sos_cmd for timestamp I get this:

timestamp
--------------------------------
               1605474253.274000
               1605474253.274000
               1605474253.274000
               1605474253.274000
               1605474253.275000
               1605474253.275000
...

What might I be doing wrong to cause this error? I would expect a secs.usecs number to be able to be imported.

**Comment by nick-enoent** [comment]
What version of numsos/SOS are you using? Are you experiencing this issue on mon1?

**Comment by bschwal** [comment]
4.3.3 and yes.

**Comment by nick-enoent** [comment]
Can you point me at the schema and map files you're using to import this csv file, as well as the container itself? It looks like the version of SOS installed on mon1 is older (commit from January), and doesn't include the python3 patch I wrote earlier this year.

**Comment by bschwal** [comment]
Emailing you separately.

**Comment by bschwal** [comment]
Issue was due to using an improper number for the timestamp bounds in the where clause of the source select.
