### ISSUE TITLE
Error assigning float value to timestamp using sos-import-csv

### ISSUE THREAD

**Issue by bschwal** [ovis-hpc/sos#41]
I'm trying to use sos-import-csv to import a csv file into a sos container. 
My timestamps in the csv are of the kind: 1618442048368.290039 and I am trying to import them as type "timestamp." 
For these values I get the error raised in Sos.pyx line 3853: 
Error assigning {0} to timestamp. "The time value of a floating point number must be non-negative"

Looking at the code, I could not find a definitive reason why this would be the case. Importing the number as a float cut off the decimal values of the timestamp, which are necessary given the precision of the data. 

Any help appreciated!

**Comment by tom95858** [comment]
There are some fixes for timestamp assignment in the top of tree. The line you are quoting is from an old build I think.

**Comment by bschwal** [comment]
Tom, I don't see any changes to Sos.pyx or any other code in SOS-4 (what I thought was called top of tree) in 5 months. I built this within the last two weeks.

**Comment by bschwal** [comment]
For context, the use case here is I'm trying to import application data csv's into a container.

**Comment by bschwal** [comment]
Don't know why I didn't see this error before, but there is a =n error line at 3850 that the value is too large to assign to an integer. 
Perhaps changing secs and usecs to uint64 instead of int in that section?

**Comment by nick-enoent** [comment]
In Python3 the int type is unbounded, so I'm inclined to believe there's some other strange value getting passed to the sos-import-csv command. Can you see the value of the timestamp that failed to import?

**Comment by bschwal** [comment]
Nick, Tom just pushed a fix for it. I am testing the fix now and then will close this issue.

**Comment by bschwal** [comment]
Issue was solved with new push, thank you!
