### ISSUE TITLE
Cannot schema.alloc() in newer versions of SOS

### ISSUE THREAD

**Issue by bschwal** [ovis-hpc/sos#76]
I am working on SOS-6 commit 929fcc858bec6e263b2f91ff357d554ffb51f968. 
I recently created a new container with a variety of LDMS schema in it. I am trying to add records manually to one of these schema using the python API. To do this, I setup a SosDataSource(), configure it with a Sos.Session, and perform a get_schema. I.e.

data_sess = Sos.Session('/opt/ovis/system.conf')
data_cont = data_sess.open('/storage/system/sos/database')
data_src = SosDataSource()
data_src.config(cont=data_cont)
schema = data_src.get_schema('my_schema')

With new containers when I try to do an alloc on schema I get a failure:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Sos.pyx", line 1836, in python.Sos.Schema.alloc
  File "Sos.pyx", line 231, in python.Sos.SosObject.abort
Exception: Invalid argument

For what it's worth I can still do schema.name(), schema.attr_count(), etc. 

With old containers I do not get this error.

This is preventing me from moving forward with Ben Allan's process tracking analysis FYI.  Any help appreciated.

**Comment by nick-enoent** [comment]
When allocating objects to a container directly, you must configure SosDataSource with a container object, or a path to a container, rather than using a Session class object to open the container.
