### ISSUE TITLE
Does show(limit=N) include the header in N?

### ISSUE THREAD

**Issue by oceandlr** [ovis-hpc/sos#9]
See example below. Limit = 4 and it says it out put 4 records, but there are only 3. Does the header count toward the number?

In [5]: src.select(['timestamp','component_id','Active','MemTotal'], from_ = ['meminfo_E5-2698'], order_by='comp_time')

In [6]: src.show(limit=4)
meminfo_E5-2698                                                 
timestamp       component_id    Active          MemTotal        
--------------- --------------- --------------- --------------- 
(1518803953, 3055)              12           82672       131899340 
(1518803954, 2905)              12           82672       131899340 
(1518803955, 2761)              12           82672       131899340 
--------------- --------------- --------------- --------------- 
4 record(s)

**Comment by tom95858** [comment]
That was not the intention, no
